// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8OZafKzH4nHWdy6kS5YOXIbmggEdT7Zo',
    appId: '1:205253672777:web:c5b83bae531716acdb6498',
    messagingSenderId: '205253672777',
    projectId: 'atheletech',
    authDomain: 'atheletech.firebaseapp.com',
    storageBucket: 'atheletech.firebasestorage.app',
    measurementId: 'G-J5ERKQLQCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpAKRyOnTlieZPuxWJD2-1zQczQG0-v2s',
    appId: '1:205253672777:android:8d7baef39e1c1435db6498',
    messagingSenderId: '205253672777',
    projectId: 'atheletech',
    storageBucket: 'atheletech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdwW7TgE5eVRBReeZGaRq41ZlFsCl3hug',
    appId: '1:205253672777:ios:70916e02db7b9fb4db6498',
    messagingSenderId: '205253672777',
    projectId: 'atheletech',
    storageBucket: 'atheletech.firebasestorage.app',
    iosClientId: '205253672777-kbvpmfts707jfpu2cgajn1g2cnvqgok5.apps.googleusercontent.com',
    iosBundleId: 'com.example.athletech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdwW7TgE5eVRBReeZGaRq41ZlFsCl3hug',
    appId: '1:205253672777:ios:70916e02db7b9fb4db6498',
    messagingSenderId: '205253672777',
    projectId: 'atheletech',
    storageBucket: 'atheletech.firebasestorage.app',
    iosClientId: '205253672777-kbvpmfts707jfpu2cgajn1g2cnvqgok5.apps.googleusercontent.com',
    iosBundleId: 'com.example.athletech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8OZafKzH4nHWdy6kS5YOXIbmggEdT7Zo',
    appId: '1:205253672777:web:cd1e08a5685dd267db6498',
    messagingSenderId: '205253672777',
    projectId: 'atheletech',
    authDomain: 'atheletech.firebaseapp.com',
    storageBucket: 'atheletech.firebasestorage.app',
    measurementId: 'G-ELMSEJJGB3',
  );

}